before_commands:
    - composer install
checks:
    php: true
filter:
    excluded_paths:
        - 'tests/*'
        - 'templates/*'
build:
    environment:
        php: '7.4'
    tests:
        override:
            -
                command: 'phpunit --bootstrap vendor/autoload.php --coverage-clover=coverage-file tests'
                coverage:
                    file: 'coverage-file'
                    format: 'clover'
